### ISSUE TITLE
consider not using zmq for rpc layer

### ISSUE THREAD

**Issue by untzag** [wright-group/bluesky-autonomic#2]
the json-rpc layer might be more generally useful if it wasn't routed via zmq

**Comment by untzag** [comment]
honestly fastapi is probably a better approach than jsonrpc...

**Comment by ksunden** [comment]
fastapi doesn't have pub/sub, does it? is that not the main feature we need here?

**Comment by untzag** [comment]
At the moment we have both RPC and pub/sub.
